BASE=../../../..

LOCAL_LDFLAGS=-lflite_cmu_time_awb \
	-lflite_cmu_us_awb \
	-lflite_cmu_us_kal \
	-lflite_cmu_us_kal16 \
	-lflite_cmu_us_rms \
	-lflite_cmu_us_slt \
	-lflite_cmulex \
	-lflite_usenglish \
	-lflite

include $(BASE)/build/modmake.rules
